### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by jchannon** [RLovelett/vscode-swift#23]
Is this project still alive?

Would love for this to take off. Xcode is terrible quite honestly :)

**Comment by RLovelett** [comment]
Very much not dead!

I've had to pivot a few times on where this thing is going. I do not want to maintain the extension like I had started. I wanted something that was going to be a little bit more robust. So I first was looking into doing it as a [Node.js and SourceKit](https://github.com/RLovelett/node-sourcekit) integration.

Unfortunately that hit a snag regarding building against the version of Electron that VS Code uses.

So I have pivoted again and now I'm [implementing a language server](https://github.com/RLovelett/langserver-swift). When I complete that task I'll be circling back here to integrate the two.

Aside from the fact that I think the language-server is the way to go to work around the Electron issues. I think it also has other added benefits. It effectively means that all of the editors that support the [language server protocol](https://github.com/Microsoft/language-server-protocol) also will immediately gain Swift support. Additionally since I'm writing it in Swift hopefully the audience will be able to help improve/maintain it.

If your interested in helping I'm interested in accepting help over at the https://github.com/RLovelett/langserver-swift.

**Comment by RLovelett** [comment]
I just wanted to say that the language server has taken a little bit longer than I hoped. SwiftPM is not simple to work with yet. I am however making headway.

**Comment by jchannon** [comment]
Good stuff!

**Comment by fortinmike** [comment]
Your effort is greatly appreciated. Thanks for working on this! I'm looking forward to using your extension for Swift scripting :)

**Comment by jchannon** [comment]
I wonder if there are any blogs/community we can make this more public and
get some help/contributors going?

**Comment by RLovelett** [comment]
I've given @aaroncrespo collaborator access to this repository and would likely do the same for anyone interested in helping on [langserver-swift](https://github.com/RLovelett/langserver-swift).

The largest struggle I'm having right now is just establishing a scaffold for the repository, e.g., getting a reproducible environment and getting into a development groove.

I had hoped that creating a testable executable using SwiftPM would be easy. So far that has not been my experience. Between packages just not supporting SwiftPM (and others [_ONLY_ supporting SwiftPM](https://github.com/IBM-Swift/BlueSocket)). [Or just adding test fixtures](https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20161114/003987.html). This has _really_ slowed my development down.

I'd go away from SwiftPM and just do a standard macOS command-line application except that some of my dependencies won't support that (not to mention I want this to work on Linux). Which means I'd either need to modify those deps or find new ones.

I say all of that to say that my largest struggle right now is just getting the ship off the ground so to speak. Once I have a scaffold to work in _then_ having more help I think would really be beneficial.

**Comment by RLovelett** [comment]
[Just released a new version that _should_ hopefully bring support to Swift 3.1 and further.](https://github.com/RLovelett/vscode-swift/releases/tag/0.1.0)

**Comment by jchannon** [comment]
Good stuff, installed latest version and latest sourcekitten, opened vscode, changed new file to be swift syntax and get an error.

<img width="1103" alt="screen shot 2016-12-12 at 21 25 18" src="https://cloud.githubusercontent.com/assets/105126/21117682/a3ad4068-c0b2-11e6-81c5-3e03fbaab733.png">

**Comment by RLovelett** [comment]
I've switched to a new backend. It no longer uses SourceKitten.

It now uses a special Swift language server. https://github.com/RLovelett/langserver-swift/blob/master/README.md

You need to build that and install it. Not it doesn't have to be in `/usr/local/bin` but that's the default.

**Comment by jchannon** [comment]
Gotcha!

Got this...

<img width="1099" alt="screen shot 2016-12-12 at 22 20 42" src="https://cloud.githubusercontent.com/assets/105126/21119182/4e0cbdbc-c0b9-11e6-8616-7079ca46a651.png">

**Comment by RLovelett** [comment]
What version of Swift? Specifically which version of SwiftPM?

It requires a snapshot version of SwiftPM to compile.

**Comment by jchannon** [comment]
Ah, dont think i have the snapshot installed. Thanks

**Comment by RLovelett** [comment]
Yeah I'm disappointed in what I had to do. But I was having so many troubles with dependency management bugs in SwiftPM that going to a snapshot was basically my only choice.

Good news Swift 3.2 should be out early next year which will include all the necessary changes.
